### ISSUE TITLE
Shading Normal for Displaced Micro-Mesh?

### ISSUE THREAD

**Issue by shocker-0x15** [NVIDIAGameWorks/Displacement-MicroMap-Toolkit#7]
Hello,

I'm not sure if here is the right place to ask. Let me know if there is a better place (e.g. somewhere in NVIDIA forum).

Now I can render a detailed mesh generated by DMM SDK (micromesh toolbox) in my program with a low base triangle count.
![image](https://github.com/NVIDIAGameWorks/Displacement-MicroMap-Toolkit/assets/4602478/830fd948-dc8f-45d3-a35f-a11ef99d6355)

However while the mesh looks well detailed overall, micro triangles look flat since we don't have "micro-vertex normals" from which we interpolate a shading normal.
![image](https://github.com/NVIDIAGameWorks/Displacement-MicroMap-Toolkit/assets/4602478/fa831551-b70a-4ae4-bb92-9f6dee4e16a5)

I guess we need some texture instead of the micro-vertex normals to represent the shading normals although I'm not sure if we can represent them with a reasonable texture size.

So I assume the case where I have:
- a high poly mesh with vertex normals without a normal texture
- (optionally) have a low poly mesh without any textures

Is there a workflow/function in DMM SDK to represent smooth normal for displaced micro-mesh?

Thanks

**Comment by pknowlesnv** [comment]
Hi. Yes, normal maps are the way to go for now. It does require the base mesh to have UVs. The tools here can create the normal map based on the refrence mesh geometry. To trigger that path, resampling needs to be enabled (e.g. `bake --resample all` or the equivalent in the UI) and the reference mesh needs to have a normal map (even if it's flat, `#8080ff`). For an example, the [Crab](https://developer.download.nvidia.com/ProGraphics/nvpro-samples/reefcrab.7z) mesh sample has been given such a normal map and when resampled for the base mesh a regular normal map is produced. There is some discussion in [docs/examples.md](https://github.com/NVIDIAGameWorks/Displacement-MicroMap-Toolkit/blob/main/docs/examples.md).

<img src="https://github.com/NVIDIAGameWorks/Displacement-MicroMap-Toolkit/assets/22082237/8a31db0f-343f-42d3-b6fe-ef1f524849e2" width="200px" />

Given tooling it would be possible to store per-micro-vertex normals much like the `.bary` file stores displacements but this isn't currently supported by the tools or renderers here.

**Comment by shocker-0x15** [comment]
Thanks for the reply.

Let me clarify some points to make sure.

The normal map of the reference crab mesh seems completely flat `#8080ff`.

1. So does this mean normal map is applied on top of interpolated normal (and interpolated UV direction vectors corrected to be perpendicular to the normal)?
    - Is this the standard way? (just want to know)\
    Another possibility is applying normal map on top of the geometric normal basis.
2. Which of the followings is assumed?\
Generated normal map is applied on top of
    a. shading normal interpolated from "base" vertex normals
    b. geometric normal of the base triangle

> store per-micro-vertex normals much like the .bary file stores displacements

This sounds interesting. Do you mean we decompress them by SW or does Ada supports some secret feature :) ?

**Comment by pknowlesnv** [comment]
Normal maps for the base and reference meshes are just regular normal maps, defined in tangent space. There is no micro-triangle tangent space for micromeshes, and I can see why this might be surprising. That is, normal map values come from an interpolation across the whole base triangle, just as would be done if micromeshes weren't used, and micro-vertices do not need to be considered.

Yes, the normal map is applied on top of the interpolated normal and tangent vectors. The tangent space basis vectors (tangent, bi-tangent and normal) are defined per vertex in object space, interpolated across the triangle, and the normal map value represents a combination of them.

Re. "geometric normals", if I'm understanding correctly, this doesn't work but I think it's interesting to explore. It is possible to create a normal map where the tangent space uses a flat normal and constant tangent vectors across the whole triangle. Tangent vectors are typically smoothed at shared vertices - [the code here](https://github.com/NVIDIAGameWorks/Displacement-MicroMap-Toolkit/blob/00fde4a2a96c7110293673ccec161e2a6798b115/meshops_core/include/meshops/meshops_types.h#L88) supports a few methods to generate them when they're missing from the glTF. As long as the normal map is generated using the same tangent space, the same normals should be produced _at those sample locations_ when reading it back. The problem happens at the in-betweens. Assuming the normal map needs to define a smooth surface between two triangles, the tangent space normal would have a sharp change at shared triangle edges. Due to interpolating normal map texture values (e.g. with bi-linear filtering) there would be some values leaking across the edge. If instead, tangent space is smoothly interpolated across the triangle, the normal map to represent just that smooth surface can be a constant  `#8080ff` and interpolation doesn't matter anymore.

<img src="https://github.com/NVIDIAGameWorks/Displacement-MicroMap-Toolkit/assets/22082237/7e56d81f-c3ce-456c-b11b-789003460b44" width="180px" />

Re. per-micro-vertex normals. Unfortunately attribute compression is not handled by the SDK (only micro-vertex displacements) and it's left to the application to implement something. For a basic example, a raw vec3f array of object space normals would do the job (just like regular normals for a triangle mesh) but would take a lot of memory. Dropping it to 8 bits per component would help a lot, maybe with something like _octahedron normal vectors_.

**Comment by shocker-0x15** [comment]
Wow, thanks for detailed explanation!
Now I feel all the unclear points disappear. Regarding geometric normals, your point makes sense.

I guessed per-micro-vertex normals can be appealing if its (compressed) total size and performance in shading is competitive with the above normal map approach since there is no optimal resolution issue that seems to exist in the normal map approach. (Well this approach may have another issue on the other hand)

Thanks, very much again!

**Comment by shocker-0x15** [comment]
Let me report the last thing.
I could have confirmed that the normal map approach can represent shading normals between micro vertices!

![image](https://github.com/NVIDIAGameWorks/Displacement-MicroMap-Toolkit/assets/4602478/c7988690-f6d7-4f27-9d44-504bcee447ed)
